component Button inherits Rectangle {
    in-out property text <=> txt.text;
    in-out property font-size <=> txt.font-size;
    callback clicked <=> touch.clicked;
    border-radius: root.height / 2;
    height: txt.preferred-height * 1.33;
    min-width: txt.preferred-width + 20px;
    txt := Text {
        x: (parent.width - self.width)/2 + (touch.pressed ? 2px : 0);
        y: (parent.height - self.height)/2 + (touch.pressed ? 1px : 0);
        color: touch.pressed ? #fff : #eee;
    }
    touch := TouchArea { }
}
export component WhatsOnTheMenu inherits Rectangle{
    width: 100%;
    height: menubar.min-height;
    background: #333;
    y: 0;
    x: 0;

    menubar := HorizontalLayout {
        alignment: start;
        file := Button {
            text: "File";
            clicked => {filepopup.show()}
        }

        edit := Button {
            text: "Edit";
            clicked => {editpopup.show()}
        }

        Button {
            text: "Settings";
        }

        Button {
            text: "Effects";
        }

        Button {
            text: "Animation";
        }
    }

    filepopup := PopupWindow {
        x: file.x; y: 20px;
        Rectangle {
            background: #333;
            border-radius: 12px;
            VerticalLayout {
                alignment: start;
                Button {
                    text: "New";
                    font-size: 10px;
                }
                Button {
                    text: "Open";
                    font-size: 10px;
                }
                Button {
                    text: "Open Recent";
                    font-size: 10px;
                }
            }
        }
        
    }

    editpopup := PopupWindow {
        x: edit.x; y: 20px;
        Rectangle {
            background: #333;
            VerticalLayout {
                alignment: start;
                Button {
                    text: "Undo";
                    font-size: 10px;
                }
                Button {
                    text: "Redo";
                    font-size: 10px;
                }
            }
        }
    }
}   