export component SplashScreen inherits Window {
    width: 600px;
    height: 400px;
    background: #2b2b2b;  // Background color
    no-frame: true;
    title: "Splash Screen";

    in property <string> version: "ver N/A";

    VerticalLayout {
        alignment: center;
        
        Text {
            text: "Aetherea";
            color: white;
            font-size: 30px;
            horizontal-alignment: center;
        }
    
        Text {
            text: version;
            color: gray;
            font-size: 16px;
            horizontal-alignment: center;
        }
    }
    
}
